### ISSUE TITLE
webpack-encore-bundle version 2

### ISSUE THREAD

**Issue by BelleNottelling** [lcharette/webpack-encore-twig#3]
Hi there, thanks for the project!
We've been using it in the FOSSBilling project and all is working well, however I've noticed the package isn't yet updated to allow V2 of the `symfony/webpack-encore-bundle` package. v2 only dropped the deprecated functionality and increased the minimum PHP version, so all you need to do is update your `composer.json` file to allow both v1 and v2 of the package.

I've already validated that things work correctly with this upgrade in our application by leveraging composer's alias functionality (`"2.1.1 as 1.17.2"`), but that's not as nice of a solution as simply just having things work.

Thanks again!

**Comment by lcharette** [comment]
Fixed, and released as 1.2.0 👍
